### ISSUE TITLE
Non-numerical thread amounts are allowed, causing update and verification softlocks.

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#13]
### Summary
When OFToast has letters or symbols in the threads amount setting, you can get stuck infinitely waiting for an update or verification. This is an issue similar to #10.

![Screenshot_20230128_090847](https://user-images.githubusercontent.com/18003771/215279549-164540c0-e0b8-4b62-af8a-eec8daeca0d6.png)
![Screenshot_20230127_204337](https://user-images.githubusercontent.com/18003771/215242436-6cac1fb1-040b-4241-90a9-9c54e35b9195.png)

### Step to reproduce
1. Launch OFToast
2. Navigate to Advanced.
3. Change the number of threads to an alphanumeric string, containing Latin letters or symbols. 
4. Click Advanced again to close the menu
5. Click Verify or Update

### What I expected
OFToast should not allow me to have letters or symbols as an acceptable input and should hand me an error prompt.

### What actually happened
It lets me proceed up to the verification and update process, which causes a softlock.

### Additional notes
- Non-English inputs do not get copied over into this field already and won't cause issues (ex. 우유2 will be accepted as just 2).
- You can have a mix of symbols / letters and numbers, but the inclusion of the latter will notify OFToast that this is an invalid number of threads (ex. ABC is acceptable but ABC23 is invalid).

### System Specifications
- **OFToast Version:** v0.0.0-alpha2
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.7-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.3
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment]
root cause is the same as #10.

**Comment by Sloofy** [comment]
Issue fixed in v0.0.0-alpha3 - now properly considers letters and symbols as invalid.
