### ISSUE TITLE
Advanced settings softlock when using input popup

### ISSUE THREAD

**Issue by NotQuiteApex** [int-72h/oftoast-godot#15]
Moving this from the Discord to here for proper documenting.

When using the input popup box when an incorrect number of threads is entered, its possible to lock yourself into the advanced settings menu without being able to exit.

### Steps to reproduce
1. open toast
2. click advanced
3. click in the thread count box, type some number greater than 4
4. error box pops up. type some number between 1 and 4 in the input
5. press input, box wont disappear
6. press input again, window disappears but you cant exit advanced and the thread count box stays the same (same as in step 3)

### System Specifications
* OFToast Version: v0.0.0-alpha2
* OS: Windows 11 (64 bit)
* CPU: AMD Ryzen 5 3800x
* GPU: Nvidia RTX 3070

**Comment by int-72h** [comment]
for posterity, the issue is that the ``check_options()`` wouldn't return to the previous function when done due to a incorrect ``yield()`` in the previous function.
should be fixed in the next commit.

**Comment by int-72h** [comment]
Please test this with alpha3.

**Comment by NotQuiteApex** [comment]
Clicking retry now softlocks in the same way, however input works as intended (changes the value in the settings box, popup disappears, and advanced menu can be exited).

**Comment by NotQuiteApex** [comment]
Input box does not appear to check what it has in the box and will place anything inside the thread count box.

**Comment by int-72h** [comment]
That's normal - the check comes after the input button has been pressed.

**Comment by NotQuiteApex** [comment]
Sorry, should've mentioned that it accepts the input and exits the advanced menu as well, leaving the bad value in the box unchecked.

**Comment by int-72h** [comment]
hmm, can you provide a video to show this in action?

**Comment by NotQuiteApex** [comment]
https://cdn.discordapp.com/attachments/1068691610046570577/1069006333719887872/2023-01-28_16-28-01.mp4

Cross-posting from Discord.

**Comment by int-72h** [comment]
Will be fixed in next commit

**Comment by NotQuiteApex** [comment]
Fixed as of alpha4 thanks to new input sanitizing.
