### ISSUE TITLE
Updating and Verifying currently non-functional on my end.

### ISSUE THREAD

**Issue by DustyDalken** [int-72h/oftoast-godot#16]
It's in the name. No toast spinning, no toaster dinging (although there is a quieter sound) just a perpetually empty verifying progress bar. This is not the case with the first pre alpha at all, only the second. Here's footage.

1. OFTOAST II alpha 1
https://user-images.githubusercontent.com/85916614/215282965-030a6d3b-caf2-475c-9026-d328c512d28e.mp4

2. OFTOAST II alpha 2
https://user-images.githubusercontent.com/85916614/215282972-5c3e1257-b610-4a39-8c48-0b5d1f1448fe.mp4

**Comment by int-72h** [comment]
I've tried to fix this but it seems to keep cropping up...

**Comment by int-72h** [comment]
Reopen if this keeps happening.
