### ISSUE TITLE
Blog posts "pull" each other on either end when selected

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#17]
### Summary
When the user selects a blog post from the far left or far right, it will subsequently shuffle the rest of the posts towards that general direction. This is contrasted to behaviour when selecting the centre post and going back to the original selection, which does not move anything on the horizontal axis.

https://user-images.githubusercontent.com/18003771/215286909-72edfc14-f935-428c-afb2-1010a1a008b9.mp4

### Step to reproduce
1. Launch OFToast
2. Select a blog post from either farthest side (first or third post from left-to-right order).
3. Observe the tabs position change.

### What I expected
The blog posts probably should not be moving around like this.

### What actually happened
The whole stack of blog posts get pulled in the direction towards your selection.

### Additional notes
- Clicking the centre post only shuffles the post next to what was previously selected.
- If this behaviour is done intentionally to show the user what they have selected, I think it's better to vertically raise the tab than to horizontally adjust it.

### System Specifications
- **OFToast Version:** v0.0.0-alpha2
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.7-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.3
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment]
This was a LOT worse when I was first doing the blog panel theming... 
I don't think it's that much of a big issue personally, and i'm not sure if it's possible since all the blogpanel stuff is in engine.
Closing for now.

**Comment by Sloofy** [comment]
> and i'm not sure if it's possible since all the blogpanel stuff is in engine.

When you mean "if it's possible", can you elaborate on what you mean by that?

**Comment by int-72h** [comment]
I mean more faesible.
The current blogpanel uses a ``TabContainer`` node which is built into godot (i.e I don't have to write any code to change the tabs, render them, etc), if I were to roll my own it would be a lot more effort, be possibly buggier, add complexity and the end result may not even be that much better.

**Comment by Sloofy** [comment]
Would it be possible, then, to change the selection behaviour to light up on current selection or to raise vertically instead of horizontally? If not, totally alright. The current behaviour is sufficient enough to communicate selection.
