### ISSUE TITLE
The "Advanced Options" title is not centred

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#18]
### Summary
By and large, this is a nitpick, but figured I should note it down. The title text here is not centred in the middle.

![Screenshot_20230128_112147](https://user-images.githubusercontent.com/18003771/215287204-5aab4320-4981-47f1-93ed-d6182d68266e.png)

### Step to reproduce
1. Launch OFToast
2. Go into Advanced
3. Observe title

### What I expected
It should probably be centred.

### What actually happened
It's slightly adjusted to the left.

### Additional notes
- It's probably a carryover from the "Latest from the blog" text as they're in similar starting positions, though this is just a guess.

### System Specifications
- **OFToast Version:** v0.0.0-alpha2
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.7-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.3
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment]
...will be fixed in next release

**Comment by Sloofy** [comment]
Issue resolved as of v0.0.0-alpha4
