### ISSUE TITLE
Text fields lack a blinking cursor

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#19]
### Summary
In all input fields, there is no blinking cursor to help indicate where the user is currently selected and ready to type in. This feedback would otherwise inform whether the program is anticipating a response.

### Step to reproduce
1. Launch OFToast
2. Go into Advanced
3. Click on either input fields (currently either number of threads or mirrors).

### What I expected
There should be a blinking line on the currently selected portion to let the user know where they are about to type in.

### What actually happened
There isn't one, which keeps the user guessing if they're able to type and precisely where they are.

### System Specifications
- **OFToast Version:** v0.0.0-alpha3
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.7-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.3
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment]
Will be fixed in next commit.

**Comment by NotQuiteApex** [comment]
Cursor is noticeable in the threads field, but hasn't changed in the mirrors field and neither blink.

**Comment by Sloofy** [comment]
>  but hasn't changed in the mirrors field

There is actually a cursor in the mirrors field, but it's really hard to make out because it's white. Wedged in-between the 4 S's highlighted in this screen, that is the cursor. Depending on your monitor settings and lighting situation, you may not be able to see it.
![image](https://user-images.githubusercontent.com/18003771/215303563-cae4e7b6-b646-4ee9-89e3-13da8c622564.png)

Higher contrast image:
![Screenshot_20230128_194505](https://user-images.githubusercontent.com/18003771/215303692-e36bc900-049e-4fe6-b55e-fe7fd9be96d5.png)

**Comment by int-72h** [comment]
Will be fixed in next release
