### ISSUE TITLE
Links do not open in browser

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#21]
### Summary
In blog posts, posts with links in them don't open in an external browser. Hovering over them will give visual cursor feedback that the item is clickable, however.

![Screenshot_20230128_134641](https://user-images.githubusercontent.com/18003771/215292554-ca833123-05f3-47ce-958a-7f4004ede815.png)

### Step to reproduce
1. Launch OFToast
2. Find a blog post that has a link in it (Currently, "Go, Move It!" has two as "download page" (first sentence) and "here" (last sentence)).
3. Click on the text.

### What I expected
The link should open up in an external browser. In canonical order from those listed above, it should open https://openfortress.fun/blog and https://github.com/brysondev/OF-Install-Script/blob/main/README.md

### What actually happened
Clicking on the links does nothing.

### System Specifications
- **OFToast Version:** v0.0.0-alpha3
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.7-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.3
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment]
This one I've been aware of but just haven't gotten around to doing.

**Comment by int-72h** [comment]
Should be fixed in next release.
