### ISSUE TITLE
Able to force update on latest revision by accessing Advanced menu

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#23]
### Summary
If you're on the latest revision, you can force OFToast to update by reopening the main menu through the Advanced menu. It's implied this behaviour shouldn't be happening because we're only fetching updates if we have a revision number that mismatches the latest.

### Step to reproduce
1. Launch OFToast
2. Be on the same revision number as the latest (ex. if current is 12, then we are on 12).
3. Observe that on the latest revision, you cannot update
4. Go into Advanced
5. Return back to the main menu

### What I expected
The update button should continue to be greyed out because we still have a revision that matches the latest number.

### What actually happened
I can continue with an update process, though it's really just verifying the files are there.

### System Specifications
- **OFToast Version:** v0.0.0-alpha4
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.7-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.3
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment]
should be fixed in alpha5

**Comment by Sloofy** [comment]
Issued resolved as of v0.0.0-alpha5
