### ISSUE TITLE
[Request] check if file is already present on install

### ISSUE THREAD

**Issue by Jan200101** [int-72h/oftoast-godot#29]
### Summary

If no revision information is available Toast simply downloads objects and saves them where they are suppose to go.

On installations with no revision information this will spend time downloading and writing files that are already on disk

**Comment by int-72h** [comment]
This will be fixed by performing a verification (which in essence checks the FS for existing files) before anything else (with appropriate "checking..." instead of "verifying..." text)

**Comment by int-72h** [comment]
This can/will be added in by doing a verification pass if there's no install - will be added shortly

**Comment by int-72h** [comment]
...Actually I decided to fix this in a slightly more pragmatic way, if an OF install isn't detected (but a path is), the verify box will be able to be pressed, and it'll say "Check for existing installs" instead.
