### ISSUE TITLE
[Request] Add a option to make a copy of your saves from a failed/corrupted download or game

### ISSUE THREAD

**Issue by ArielChandia2** [int-72h/oftoast-godot#36]
### Summary:

With latest downloads from open fortress last year, it suffer a lot of crashes and corrupted files from servers errors when a update relased, i had to manually download a mirror loosing my save data and having to recreate all of my config again, So it would be preferable to make an option to make a copy of your saves or configs, (or skin customization) so you can drag and drop on a new build.

### What I expected:

The option could be in advanced options or it could be a pop up windows if the downloads fails, and its created in a easy to reach folder like the documents or downloads folder with the files copied to drag and drop in a new downloaded build.

**Comment by int-72h** [comment]
I don't see how a corrupted install would delete your configs.
Murse or oftoast 1 did seem to have a habit of nuking the install folder but this is quite notably a non-issue with toast 2 and is a bit out of scope. We can't tell which configs are user-edited and which aren't. 
I will whitelist the config folder from changes, or at least move old versions to .old or something though.
