### ISSUE TITLE
Segmentation fault when leaving Advanced Menu if no Open Fortress folder exists

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#41]
### Summary
When the user does not have a `open_fortress/` folder where OFToast expects it (ie. a new user or the install path does not find one), leaving the Advanced Menu crashes the application entirely. This is fixed when the folder is created upon reopening OFToast.

This was tested using Steam (native and flatpak) and without Steam installed. The terminal output bellows happens regardless of Steam installation.

![image](https://user-images.githubusercontent.com/18003771/222939064-9002f64e-4941-47fd-854d-d04c623cb152.png)

### Step to reproduce
1. Do not have an `open_fortress/` folder where Toast expects it to be (usually `sourcemods/open_fortress/`).
2. Launch OFToast.
3. Open the Advanced Menu screen using the "Advanced" button.
4. Try to leave the menu by pressing the "Advanced" button again.

### What I expected
I should be able to return back to the main menu.

### What actually happened
OFToast crashes.

### System Specifications
- **OFToast Version:** v0.0.0-[gitcommit](https://github.com/Superdiffusion/oftoast2/commit/dd77c3a67cd41a9a7d772d898aa99a8e1167af34)
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.14-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.6
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment]
Yeah I can't seem to reproduce this without the OF folder - It'll take a bit to figure this out.

**Comment by int-72h** [comment]
Closing, if you're able to reproduce this consistently on the latest commit, then please reopen.
