### ISSUE TITLE
Seemingly indefinite verify process when game hasn't been installed

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#42]
### Summary
When OFToast succesfully finds `/sourcemods/open_fortress/` but has not yet installed the game, the verifying procedure will seemingly last forever.

This was tested using Steam (native).

![image](https://user-images.githubusercontent.com/18003771/222939200-76693337-00a4-48bb-b9c8-2c6bc50174a4.png)
![image](https://user-images.githubusercontent.com/18003771/222939226-8263d4f6-0025-4204-a7cd-1aab4430b9d1.png)

### Step to reproduce
1. Have an `open_fortress/` folder where Toast expects it to be (usually `sourcemods/open_fortress/`).
2. Do not have the game's contents installed, however
3. Launch OFToast.
4. Click "Verify"

### What I expected
The process probably shouldn't proceed since we do not have the game installed yet. Instead, the button should be disabled.

### What actually happened
We can verify, and it seems to last a very, very long time.

### System Specifications
- **OFToast Version:** v0.0.0-[gitcommit](https://github.com/Superdiffusion/oftoast2/commit/dd77c3a67cd41a9a7d772d898aa99a8e1167af34)
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.14-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.6
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment]
Can you include the whole debug output if possible?

**Comment by Sloofy** [comment]
Wasn't able to get the whole output because of the mismatch spam. At the end, it should be noted that I forcefully quit the application. [output.txt](https://github.com/Superdiffusion/oftoast2/files/10902662/output.txt)

**Comment by int-72h** [comment]
OK so what's happened is it's ran the verification, realised nothing's there so mismatches everything, then tried to download the zip (and that doesn't work at the moment).

**Comment by int-72h** [comment]
Should be fixed with the latest commit, can you confirm this is fixed?

**Comment by Sloofy** [comment]
> Should be fixed with the latest commit, can you confirm this is fixed?

On the latest commit. Verifying has been stuck at downloading the zip for a little over half an hour. The terminal has nothing new to report.

![image](https://user-images.githubusercontent.com/18003771/224612303-355ced99-2608-4da9-9c26-064f33a1665b.png)
