### ISSUE TITLE
"Failed to unzip" if game has not been installed

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#43]
### Summary
When OFToast succesfully finds `/sourcemods/open_fortress/` but has not yet installed the game, starting the update process will prompt a "failed to unzip" error. Clicking "continue" or "retry" continues the updating process, though may not actually be installing anything.

This was tested using Steam (native and flatpak).

![image](https://user-images.githubusercontent.com/18003771/222939200-76693337-00a4-48bb-b9c8-2c6bc50174a4.png)
![image](https://user-images.githubusercontent.com/18003771/222941049-0d1d6908-d10e-4031-b6bc-dd043d6f1823.png)

### Step to reproduce
1. Have an `open_fortress/` folder where Toast expects it to be (usually `sourcemods/open_fortress/`).
2. Do not have the game's contents installed, however
3. Launch OFToast.
4. Click "Update"

### What I expected
The installation process should continue as expected without any errors. After some time, the game should be installed.

### What actually happened
We are informed that we have failed to unzip and it doesn't appear that we're actually installing anything.

### System Specifications
- **OFToast Version:** v0.0.0-[gitcommit](https://github.com/Superdiffusion/oftoast2/commit/dd77c3a67cd41a9a7d772d898aa99a8e1167af34)
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.14-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.6
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment]
Should be fixed in latest commit.

**Comment by int-72h** [comment]
This should be fixed - reopen if this isn't the case.
