### ISSUE TITLE
Team fortress 2 and SDK detection doesn't work

### ISSUE THREAD

**Issue by JumbledActivity** [int-72h/oftoast-godot#44]
When launching the latest build of oftoast2 on Windows 10 22H2 x64 with a shell (with or without --verbose argument), it doesn't check for Team Fortress 2 and Source SDK. This has worked in alpha5.
Alpha 5:
[alpha5log.txt](https://github.com/Superdiffusion/oftoast2/files/10902856/alpha5log.txt)
Latest build:
[latest log.txt](https://github.com/Superdiffusion/oftoast2/files/10902857/latest.log.txt)

**Comment by int-72h** [comment]
This is because I removed it when refactoring the OF path checking code and forgot to put it back in - fix impending
