### ISSUE TITLE
OFToast reporting the incorrect latest revision

### ISSUE THREAD

**Issue by JumbledActivity** [int-72h/oftoast-godot#45]
When using the latest build of OFToast on Windows 10 22H2 x64, it reports that revision 13 is the latest. The alpha5 build reports that revision 14 is the latest.
Latest build:
![image](https://user-images.githubusercontent.com/112549238/223234521-744dd80e-8240-4957-ac4d-8c0298e8e76c.png)
Alpha 5:
![image](https://user-images.githubusercontent.com/112549238/223234732-868985ee-c614-4524-a1fd-f918a75ca694.png)

**Comment by int-72h** [comment]
Yeah this is not an issue with OFToast but since then I've set toast2 to use toastware.org's mirror instead of openfortress.fun - toastware's mirror hasn't been synced yet.
