### ISSUE TITLE
Error prompt buttons "Quit" and "Use Input" crash

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#7]
### Summary
When inserting invalid revision numbers, the "Quit" and "Use Input" buttons on the error prompt will crash OFToast.

![image](https://user-images.githubusercontent.com/18003771/215239452-c31c1234-ef19-4c5f-8a26-b4f0efd1c2e6.png)

### Step to reproduce
1. Launch OFToast
2. Navigate to Advanced.
3. Change the revision to update to a negative integer or version that's above the current one (ex. We are on revision 12, so 13 will crash).
4. Click Advanced again for the error prompt to appear.
5. Choose either Quit or Use Input.
6. Crash

### What I expected
OFToast would be able to continue functionality and let me self-correct to a valid revision number.

### What actually happened
OFToast fails to return back to the original input and crashes.

### Additional information
This only works for negative integers and numbers above the current version.

The prompt does not appear when decimal numbers (ex. 11.2) or zero are inputs.

Inputs in this screen are not saved once crashing.

### System Specifications
- **OFToast Version:** v0.0.0-alpha1
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.7-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.3
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by Sloofy** [comment]
As it turns out, this applies to more than just revision number and generally applies wherever the error prompt shows up.

**Comment by int-72h** [comment]
Fixed in v0.0.0-alpha2.
