### ISSUE TITLE
The happy toast icon does not spin in the centre

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#8]
### Summary
When an update / verification has finished, the happy toast mascot in the top-left will spin, but not in the centre. It slightly orbits around farther than it should.

The mascot in question:
![Screenshot_20230127_194929](https://user-images.githubusercontent.com/18003771/215240721-9e896eb8-842b-4abd-b6a7-3cae011828d9.png)

### Step to reproduce
1. Launch OFToast
2. Complete a verification / update
3. Watch the top-left icon spin around

### What I expected
Only the toast inside the circle would spin in place.

### What actually happened
The whole image spins around including the toast and circle, meaning the centre point of the image isn't rotated on its centre.

### System Specifications
- **OFToast Version:** v0.0.0-alpha1
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.7-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.3
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment]
This one's going to be a bit tricky.

**Comment by int-72h** [comment]
OK I revectorised it and it's a lot better now. not absolutely perfect but it's a lot less noticeable.

**Comment by Sloofy** [comment]
Looks like this is fixed proper now. Closing
