### ISSUE TITLE
Invalid threads error prompt buttons "Quit" and "Use Input" crash

### ISSUE THREAD

**Issue by Sloofy** [int-72h/oftoast-godot#9]
### Summary
When inserting invalid thread numbers, the "Quit" and "Use Input" buttons on the error prompt will crash OFToast. This is a similar issue to #7.

![Screenshot_20230127_203716](https://user-images.githubusercontent.com/18003771/215242274-f586d5cb-aa55-4f13-a733-04e10788536c.png)

### Step to reproduce
1. Launch OFToast
2. Navigate to Advanced.
3. Change the number of threads to an invalid amount (negative or higher than 4).
4. Click Advanced again for the error prompt to appear.
5. Choose either Quit or Use Input.
6. Crash

### What I expected
OFToast would be able to continue functionality and let me self-correct to a valid number of threads.

### What actually happened
OFToast fails to return back to the original input and crashes.

### System Specifications
- **OFToast Version:** v0.0.0-alpha2
- **OS:** Fedora Linux 37 (KDE Plasma) (64 bit)
- **CPU**: AMD Ryzen 5 2600 Six-Core 
- **GPU**: AMD Radeon RX 580 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.1.7-200.fc37.x86_64)
- **Driver Version**: 4.6 (Compatibility Profile) Mesa 22.3.3
- **OpenGL Version**: 4.6
- **Screen resolution**: 1920x1080

**Comment by int-72h** [comment]
Does this still occur?

**Comment by NotQuiteApex** [comment]
With #15 resolved this can also be closed, probably.

**Comment by Sloofy** [comment]
Issue resolved as of v0.0.0-alpha4
